name = "Registro"
uuid = "fdd2d076-ef21-11e9-1435-9b83d91613e2"
repo = "https://github.com/wookay/Registro.git"

description = """
private Julia package registry
"""

[packages]
3e78a19a-cc83-51d8-955b-515f39fd7955 = { name = "Bukdu", path = "B/Bukdu" }
f62fece2-b996-571a-b4c9-e662aba1c617 = { name = "H3", path = "H/H3" }
ba5e3d4b-8524-549f-bc71-e76ad9e9deed = { name = "Jive", path = "J/Jive" }
39ec1447-df44-5f4c-beaa-866f30b4d3b2 = { name = "Millboard", path = "M/Millboard" }
16905944-f982-529b-abb2-b839f98f160b = { name = "Octo", path = "O/Octo" }
197b51f5-fdb5-5f35-aa9f-0a14f35f5b28 = { name = "Poptart", path = "P/Poptart" }

073c1cdb-ba79-5cf0-be0e-910e86367be0 = { name = "Aheui", path = "A/Aheui" }
74536a68-4deb-11e9-11b7-0f9d68b886ec = { name = "Allographs", path = "A/Allographs" }
579379a2-963b-11e9-2ea7-cf2d129187a4 = { name = "Calendars", path = "C/Calendars" }
183a386c-803e-11e9-3d61-c37ffbc4bc2d = { name = "FixTwos", path = "F/FixTwos" }
09ad4e76-6632-467b-9cb3-9477a91d042b = { name = "Guo", path = "G/Guo" }
4a3431d2-40ed-11e9-0f27-4ba9bf6112e5 = { name = "Hangul", path = "H/Hangul" }
de2dd24e-0ba5-11e9-1f6d-9dc38c9c8708 = { name = "Hanja", path = "H/Hanja" }
c7ae8f22-f0e3-11e8-1168-3fc928072714 = { name = "Sexagesimal", path = "S/Sexagesimal" }
cff2b2ba-bc24-11e8-1300-3fbdf5197595 = { name = "Sunyata", path = "S/Sunyata" }
8caeadda-93d1-11e9-3946-3101ffbf397f = { name = "Taltal", path = "T/Taltal" }
c544e3c2-d3e5-5802-ac44-44683f340e4a = { name = "Tau", path = "T/Tau" }
2eda8d22-0a9d-11e9-38c1-d96e883f27f6 = { name = "ThreeKingdoms", path = "T/ThreeKingdoms" }
03681a08-6072-11e9-2981-89aa67d9ce53 = { name = "Tutte", path = "T/Tutte" }
8023b820-9328-11e9-15f4-2dd9cb9c5368 = { name = "TwitchTools", path = "T/TwitchTools" }
