name = "Registro"
uuid = "fdd2d076-ef21-11e9-1435-9b83d91613e2"
repo = "https://github.com/wookay/Registro.git"

description = """
private Julia package registry
"""

[packages]
3e78a19a-cc83-51d8-955b-515f39fd7955 = { name = "Bukdu", path = "B/Bukdu" }
f62fece2-b996-571a-b4c9-e662aba1c617 = { name = "H3", path = "H/H3" }
ba5e3d4b-8524-549f-bc71-e76ad9e9deed = { name = "Jive", path = "J/Jive" }
e2c437b3-d38f-4222-8753-dddcd5679a95 = { name = "LOLTools", path = "L/LOLTools" }
39ec1447-df44-5f4c-beaa-866f30b4d3b2 = { name = "Millboard", path = "M/Millboard" }
16905944-f982-529b-abb2-b839f98f160b = { name = "Octo", path = "O/Octo" }
197b51f5-fdb5-5f35-aa9f-0a14f35f5b28 = { name = "Poptart", path = "P/Poptart" }

073c1cdb-ba79-5cf0-be0e-910e86367be0 = { name = "Aheui", path = "A/Aheui" }
74536a68-4deb-11e9-11b7-0f9d68b886ec = { name = "Allographs", path = "A/Allographs" }
a6fc6cd4-3fa5-4fea-8105-59f5ce0140e8 = { name = "Banners", path = "B/Banners" }
592d26c2-bd6b-4478-b143-dab911307e2b = { name = "BaseballGame", path = "B/BaseballGame" }
579379a2-963b-11e9-2ea7-cf2d129187a4 = { name = "Calendars", path = "C/Calendars" }
f60b7598-7494-11e8-3704-db4df1869bdc = { name = "DataLogger", path = "D/DataLogger" }
9ce87802-5ebf-43a1-bed4-4b926cbe9236 = { name = "DiscordTools", path = "D/DiscordTools" }
c599478c-de41-4aed-94ea-b47665d7a42a = { name = "EmojiSymbols", path = "E/EmojiSymbols" }
183a386c-803e-11e9-3d61-c37ffbc4bc2d = { name = "FixTwos", path = "F/FixTwos" }
9104b031-1ea6-43fe-b007-3399d82583c1 = { name = "GithubTools", path = "G/GithubTools" }
2e65c3dc-34b6-11e9-37f8-e1bd27fe888f = { name = "GreekLetters", path = "G/GreekLetters" }
09ad4e76-6632-467b-9cb3-9477a91d042b = { name = "Guo", path = "G/Guo" }
4a3431d2-40ed-11e9-0f27-4ba9bf6112e5 = { name = "Hangul", path = "H/Hangul" }
de2dd24e-0ba5-11e9-1f6d-9dc38c9c8708 = { name = "Hanja", path = "H/Hanja" }
729f561e-57a1-4f37-ac44-406d8c1bb901 = { name = "HexGrids", path = "H/HexGrids" }
a55fb1be-7bd3-11e9-311f-dd6d474c370b = { name = "IDSes", path = "I/IDSes" }
078e6c93-a565-420a-af46-e2c4e3180690 = { name = "LoRDeckCodes", path = "L/LoRDeckCodes" }
916472c3-cd8f-4e06-b672-6b5bacc7f2b3 = { name = "LoRMock", path = "L/LoRMock" }
03c70d9c-0ed3-11e9-06d8-0580e60b4340 = { name = "Lupin", path = "L/Lupin" }
e6fe5354-34fd-11e9-0e3c-7f69bb4aca21 = { name = "Mathematics", path = "M/Mathematics" }
b78a7444-de30-11e8-1888-c787cb831373 = { name = "MyPrompt", path = "M/MyPrompt" }
c7ae8f22-f0e3-11e8-1168-3fc928072714 = { name = "Sexagesimal", path = "S/Sexagesimal" }
cff2b2ba-bc24-11e8-1300-3fbdf5197595 = { name = "Sunyata", path = "S/Sunyata" }
8caeadda-93d1-11e9-3946-3101ffbf397f = { name = "Taltal", path = "T/Taltal" }
c544e3c2-d3e5-5802-ac44-44683f340e4a = { name = "Tau", path = "T/Tau" }
2eda8d22-0a9d-11e9-38c1-d96e883f27f6 = { name = "ThreeKingdoms", path = "T/ThreeKingdoms" }
03681a08-6072-11e9-2981-89aa67d9ce53 = { name = "Tutte", path = "T/Tutte" }
8023b820-9328-11e9-15f4-2dd9cb9c5368 = { name = "TwitchTools", path = "T/TwitchTools" }
6804ed55-fbcb-417d-89ab-86a903427827 = { name = "UNIX", path = "U/UNIX" }
