name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.1.0]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: runtests
        run: |
          julia -e 'using Pkg; pkg"registry add https://github.com/wookay/Registro.git"'
          julia -e 'using Pkg; pkg"dev Guo"; pkg"test Guo"'
